# Generated by Django 5.0.3 on 2024-03-15 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='top_product',
            new_name='top_book',
        ),
        migrations.RemoveField(
            model_name='book',
            name='discount',
        ),
    ]
