# Generated by Django 5.0.3 on 2024-03-16 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='product',
            new_name='book',
        ),
    ]
