# Generated by Django 5.0.3 on 2024-03-21 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_cartitem_book_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': [('send_private_email', 'Can send Private email by user that you build')]},
        ),
    ]
