# Generated by Django 5.0.3 on 2024-03-26 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='datetime_created',
        ),
    ]
